# Generated by Django 5.0.6 on 2024-05-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="title",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
