# Generated by Django 5.0.6 on 2024-05-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0002_alter_agent_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
