# Generated by Django 5.0.6 on 2024-05-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0003_alter_agent_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="agency",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="agent",
            name="full_name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
