# Generated by Django 5.0.6 on 2024-05-10 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("referral", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="referralorder",
            name="promised_items",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="referral.referralitem",
            ),
            preserve_default=False,
        ),
    ]
