# Generated by Django 5.0.6 on 2024-05-10 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("referral", "0002_referralorder_promised_items"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referral",
            name="items",
            field=models.ManyToManyField(blank=True, to="referral.referralorder"),
        ),
    ]
