# Generated by Django 5.0.6 on 2024-05-10 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("referral", "0003_alter_referral_items"),
    ]

    operations = [
        migrations.RenameField(
            model_name="referralorder",
            old_name="promised_items",
            new_name="item",
        ),
    ]
